name: Upload Python Package

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run
      run: |
        whoami
        pwd
        ls -la

    - name: Deploy
      run: |
        echo "${{ secrets.KEY }}" > key_file
        chmod 400 key_file
        ls -la
        scp -i key_file test.py root@104.248.132.156:/opt/src
