name: Upload Python Package

on:
  push:
    branches: master

jobs:
  deploy:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    # - name: Deploy
    #   run: |
    #     echo "${{ secrets.KEY }}" > .key_file
    #     chmod 400 .key_file
    #     scp -o StrictHostKeyChecking=no -i .key_file * ${{ secrets.HOST }}

    - name: Deploy
      run: |
        whoami
        pwd
        ls -la
