# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run
      run: |
        whoami
        pwd
        ls -la

    - name: Deploy
      run: |
        echo ${{ secrets.TEST }} > key_file
        chmod 400 key_file
        scp -i key_file test.py root@104.248.132.156:/opt/src
